# Generated by Django 3.0.4 on 2020-04-02 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=25)),
                ('longitud', models.CharField(max_length=25)),
                ('urlImagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('codigo', models.CharField(max_length=25, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('latitud', models.CharField(max_length=25)),
                ('longitud', models.CharField(max_length=25)),
                ('urlImagen', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CasoCovid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True, verbose_name='date published')),
                ('fecha_hora', models.DateTimeField(auto_now=True)),
                ('confirmados', models.DecimalField(decimal_places=10, max_digits=10)),
                ('recuperados', models.DecimalField(decimal_places=10, max_digits=10)),
                ('muertos', models.DecimalField(decimal_places=10, max_digits=10)),
                ('activos', models.DecimalField(decimal_places=10, max_digits=10)),
                ('nuevos', models.DecimalField(decimal_places=10, max_digits=10)),
                ('total', models.DecimalField(decimal_places=10, max_digits=10)),
                ('fk_pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidecapi.Pais')),
                ('fk_provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidecapi.Provincia')),
            ],
            options={
                'db_table': 'CasoCovid',
            },
        ),
    ]
