# Generated by Django 3.0.4 on 2020-04-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidecapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pais',
            name='provincias',
            field=models.ManyToManyField(through='covidecapi.CasoCovid', to='covidecapi.Provincia'),
        ),
    ]
