# Generated by Django 3.0.4 on 2020-04-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidecapi', '0002_pais_provincias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casocovid',
            name='fecha',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='casocovid',
            name='fecha_hora',
            field=models.DateTimeField(),
        ),
    ]
