# Generated by Django 3.0.4 on 2020-04-02 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidecapi', '0003_auto_20200402_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casocovid',
            name='fecha_hora',
        ),
    ]
