# Generated by Django 3.0.4 on 2020-04-02 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidecapi', '0005_auto_20200402_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casocovid',
            name='activos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casocovid',
            name='confirmados',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casocovid',
            name='muertos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casocovid',
            name='nuevos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casocovid',
            name='recuperados',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='casocovid',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
