# Generated by Django 3.0.4 on 2020-04-02 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidecapi', '0006_auto_20200402_1050'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pais',
            table='Pais',
        ),
        migrations.AlterModelTable(
            name='provincia',
            table='Provincia',
        ),
    ]
