# Generated by Django 3.0.4 on 2020-04-03 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidecapi', '0008_auto_20200403_0131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pais',
            old_name='pvs',
            new_name='provincias',
        ),
    ]
